server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/demo
    username: root
    password: rootroot
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      event:
        merge:
          entity_copy_observer: "allow"
      ddl-auto: validate

    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: update
              create-target: create.sql
              create-source: metadata

    flyway:
      url: jdbc:postgresql://localhost:5434/demo
      user: root
      password: rootroot
      baseline-on-migrate: true