
spring:
  datasource:
    url: jdbc:tc:postgres:14.2-alpine:///integration-tests-db
    username: sa
    password: sa
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      event:
        merge:
          entity_copy_observer: "allow"
      ddl-auto: create-drop

    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: update
              create-target: create.sql
              create-source: metadata

    flyway:
      url: jdbc:tc:postgres:14.2-alpine:///integration-tests-db
      user: sa
      password: sa
      baseline-on-migrate: true